name: collection_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # SET PACKAGES
  flutter_lints: ^2.0.0
  get: ^4.6.6


flutter:
  uses-material-design: true

